### ISSUE TITLE
Ways MLang could be improved drastically

### ISSUE THREAD

**Issue by Unzor** [Battledash-2/mlang#8]
First up, I want to say that there is an error when I run index.js. 

```
/home/runner/mlang/index.js:44
                console.log(result[0] == null ? "\u001b[1;35mundefined\u001b[0m" : (result[0]?.type == "STRING" ? `\u001b[92m"${result[0].value}"\u001b[0m` : (result[0]?.type == "BOOLEAN" ? "\u001b[1;91m" + result[0]?.value + "\u001b[0m" : result[0].value)));
                                                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Second, there are so many ways that MLang could be improved. 

First up, the REPL is very inefficient. Instead of using the official REPL module, it uses Readline. If you want an example on how to use the REPL module, take a look at [index.js](https://github.com/Unzor/elephant/blob/main/index.js#L23:L31) in my Elephant REPL. 

Second, it does not use an efficient way of looking through the arguments, but I have already talked about it [here]() in my pull request.

**Comment by Battledash-2** [comment]
The only reason you get that error is because you're using an old version of Node. This was intended for use in Node 16, not below (most places like replit use node 12). The `?.` syntax isn't supported in older versions of Node.

About the "REPL" module: It doesn't seem official and I see no use. Besides, that file is only a placeholder and will be changed in the future. I have bigger priorities for this language then a repl.

**Comment by Unzor** [comment]
The REPL module is official. You can find its API documentation at https://nodejs.org/api/repl.html

**Comment by Battledash-2** [comment]
I'm not worried about the REPL. At this point in time, I could hardly have a care in the world for the REPL. I'm focused on the actual language. If you want to contribute, go ahead, but I couldn't be bothered about a REPL.
